apiVersion: v1
kind: Service
metadata:
  name: {{ include "factoryai.fullname" . }}-api
  labels:
    {{- include "factoryai.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
  selector:
    {{- include "factoryai.selectorLabels" (dict "Chart" .Chart "Release" .Release "component" "api") | nindent 4 }}
