"""initial schema

Revision ID: 998632c10c0e
Revises:
Create Date: 2026-08-06 11:47:03.150232

Mirrors ``src/factoryai/infrastructure/persistence/orm.py`` — see that module's
docstring for the deliberate deviations from ``docs/DATA_MODEL.md`` (no ``categories``
table, no ``password_hash`` column yet, enum columns as ``TEXT`` + ``CHECK`` rather than
native Postgres enums).

Beyond what autogenerate produced, this revision also installs a trigger that makes
``audit_logs`` genuinely append-only: ``UPDATE`` and ``DELETE`` are rejected at the
database level, not merely avoided by application discipline (see
``factoryai.infrastructure.persistence.orm.AuditLogRow``).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "998632c10c0e"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

_CATEGORY_CODES = (
    "'bottle', 'cable', 'capsule', 'carpet', 'grid', 'hazelnut', 'leather', "
    "'metal_nut', 'pill', 'screw', 'tile', 'toothbrush', 'transistor', 'wood', 'zipper'"
)

_AUDIT_IMMUTABILITY_TRIGGER = """
CREATE FUNCTION reject_audit_log_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only: % is not permitted', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_audit_logs_immutable
    BEFORE UPDATE OR DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION reject_audit_log_mutation();
"""

_DROP_AUDIT_IMMUTABILITY_TRIGGER = """
DROP TRIGGER IF EXISTS trg_audit_logs_immutable ON audit_logs;
DROP FUNCTION IF EXISTS reject_audit_log_mutation();
"""


def upgrade() -> None:
    """Create every FactoryAI table and the audit-log immutability trigger."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datasets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category_code", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            f"category_code IN ({_CATEGORY_CODES})",
            name="ck_datasets_category",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("category_code", sa.String(length=32), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("perceptual_hash", sa.String(length=64), nullable=True),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("storage_bucket", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("processing_status", sa.String(length=16), nullable=False),
        sa.Column("label", sa.String(length=16), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            f"category_code IN ({_CATEGORY_CODES})",
            name="ck_images_category",
        ),
        sa.CheckConstraint("label IN ('good', 'defect', 'unlabeled')", name="ck_images_label"),
        sa.CheckConstraint(
            "processing_status IN ('pending', 'validating', 'valid', "
            "'rejected', 'quarantined', 'archived')",
            name="ck_images_processing_status",
        ),
        sa.CheckConstraint("size_bytes > 0", name="ck_images_size_positive"),
        sa.CheckConstraint("width > 0 AND height > 0", name="ck_images_resolution_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("checksum_sha256"),
    )
    op.create_index(
        "ix_images_category_status_uploaded",
        "images",
        ["category_code", "processing_status", "uploaded_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role IN ('viewer', 'operator', 'ml_engineer', 'administrator')", name="ck_users_role"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("seq", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("row_hash", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("seq"),
    )
    op.create_index(
        "ix_audit_logs_resource",
        "audit_logs",
        ["resource_type", "resource_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "dataset_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("version_tag", sa.String(length=255), nullable=False),
        sa.Column("dvc_hash", sa.String(length=128), nullable=False),
        sa.Column("git_commit", sa.String(length=40), nullable=False),
        sa.Column("image_count", sa.Integer(), nullable=False),
        sa.Column("content_checksum", sa.String(length=64), nullable=False),
        sa.Column("note", sa.String(length=2000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "char_length(git_commit) = 40", name="ck_dataset_versions_git_commit_length"
        ),
        sa.CheckConstraint("image_count > 0", name="ck_dataset_versions_nonempty"),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "version_tag", name="uq_dataset_versions_tag"),
    )
    op.create_table(
        "dataset_version_images",
        sa.Column("dataset_version_id", sa.UUID(), nullable=False),
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("split", sa.String(length=8), nullable=False),
        sa.CheckConstraint("split IN ('train', 'val', 'test')", name="ck_dvi_split"),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
        ),
        sa.PrimaryKeyConstraint("dataset_version_id", "image_id"),
    )
    op.create_table(
        "experiments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mlflow_run_id", sa.String(length=64), nullable=False),
        sa.Column("dataset_version_id", sa.UUID(), nullable=False),
        sa.Column("model_family", sa.String(length=64), nullable=False),
        sa.Column("backbone", sa.String(length=128), nullable=False),
        sa.Column("hyperparameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("git_commit", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("hardware_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("failure_reason", sa.String(length=2000), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed', 'aborted')", name="ck_experiments_status"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mlflow_run_id"),
    )
    op.create_table(
        "model_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("category_code", sa.String(length=32), nullable=False),
        sa.Column("registry_name", sa.String(length=255), nullable=False),
        sa.Column("registry_version", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("artifact_bucket", sa.String(length=255), nullable=False),
        sa.Column("artifact_key", sa.String(length=1024), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            f"category_code IN ({_CATEGORY_CODES})",
            name="ck_model_versions_category",
        ),
        sa.CheckConstraint(
            "stage IN ('development', 'staging', 'production', 'archived')",
            name="ck_model_versions_stage",
        ),
        sa.CheckConstraint("registry_version > 0", name="ck_model_versions_registry_version"),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("registry_name", "registry_version", name="uq_model_versions_registry"),
    )
    op.create_table(
        "deployments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("model_version_id", sa.UUID(), nullable=False),
        sa.Column("previous_model_version_id", sa.UUID(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("environment", sa.String(length=64), nullable=False),
        sa.Column("comparison_report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.String(length=2000), nullable=False),
        sa.Column("deployed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "action IN ('promote', 'rollback', 'archive', 'reject')", name="ck_deployments_action"
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_deployments_environment_deployed_at",
        "deployments",
        ["environment", "deployed_at"],
        unique=False,
    )
    op.create_table(
        "drift_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("model_version_id", sa.UUID(), nullable=False),
        sa.Column("reference_dataset_version_id", sa.UUID(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("min_samples", sa.Integer(), nullable=False),
        sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reference_dataset_version_id"],
            ["dataset_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("model_version_id", sa.UUID(), nullable=False),
        sa.Column("dataset_version_id", sa.UUID(), nullable=False),
        sa.Column("anomaly_score", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("is_anomalous", sa.Boolean(), nullable=False),
        sa.Column("inference_time_ms", sa.Float(), nullable=False),
        sa.Column("heatmap_bucket", sa.String(length=255), nullable=True),
        sa.Column("heatmap_key", sa.String(length=1024), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("predicted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_predictions_anomalous",
        "predictions",
        ["is_anomalous"],
        unique=False,
        postgresql_where="is_anomalous",
    )
    op.create_index(
        "ix_predictions_model_version_predicted_at",
        "predictions",
        ["model_version_id", "predicted_at"],
        unique=False,
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("prediction_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("corrected_label", sa.String(length=16), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=False),
        sa.Column("region", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "corrected_label IS NULL OR corrected_label IN ('good', 'defect', 'unlabeled')",
            name="ck_feedback_corrected_label",
        ),
        sa.CheckConstraint("verdict IN ('correct', 'incorrect')", name="ck_feedback_verdict"),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    op.execute(_AUDIT_IMMUTABILITY_TRIGGER)


def downgrade() -> None:
    """Drop the audit-log immutability trigger and every FactoryAI table."""
    op.execute(_DROP_AUDIT_IMMUTABILITY_TRIGGER)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback")
    op.drop_index("ix_predictions_model_version_predicted_at", table_name="predictions")
    op.drop_index(
        "ix_predictions_anomalous", table_name="predictions", postgresql_where="is_anomalous"
    )
    op.drop_table("predictions")
    op.drop_table("drift_reports")
    op.drop_index("ix_deployments_environment_deployed_at", table_name="deployments")
    op.drop_table("deployments")
    op.drop_table("model_versions")
    op.drop_table("experiments")
    op.drop_table("dataset_version_images")
    op.drop_table("dataset_versions")
    op.drop_index("ix_audit_logs_resource", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_index("ix_images_category_status_uploaded", table_name="images")
    op.drop_table("images")
    op.drop_table("datasets")
    # ### end Alembic commands ###
